### ISSUE TITLE
tikz picture of "data points" for models

### ISSUE THREAD

**Issue by rtimms** [rtimms/BatteryModellingFlowchart#7]
make tikz layout axes with micro / macro as x and y and functionality for adding a data point for a given model

**Comment by rtimms** [comment]
includes text box and original full 3D model

**Comment by valentinsulzer** [comment]
to do
- [ ] fix text box formatting
- [ ] add labels and tick points to the axes 
- [ ] add arrows between boxes 
- [ ] inner plots

**Comment by Scottmar93** [comment]
Merged this into the rest of the poster. I think the sizes I gave you were a bit off and the text has changed size a lot. 

Note that i have also scaled your tikz image to be 0.7 of its original size just to get it to fit in with the other stuff for now but will likely be easier to work with scale=1.
